First draft for hypermedia working group
Geonovum/KP-APIs pull request #375
Opened 2021-03-16 10:57 UTC by joostfarla

Dit PR moet worden beschouwd als work-in-progress en is bedoeld als een eerste aanzet voor de subgroep hypermedia.

2021-06-03 09:56 UTC, frankvanes requested changes
Mijns inziens over het algemeen een goed stuk, een paar opmerkingen:

**API-XX: Provide absolute URIs for hyperlinks**
- Hoewel ik het hier niet mee eens ben, is het--wanneer we dit toch willen afdwingen--wellicht goed om te vermelden dat goed opgelet moet worden bij het gebruik van proxies. Wanneer een back-end systeem of microservice bijvoorbeeld een absolute URL in de response voegt, moet deze weten op welk extern endpoint de API Gateway wordt aangeboden. Dit wordt nog lastiger wanneer dezelfde API via meerdere API Gateways of via een centrale dienst als het Centraal Aansluitpunt wordt aangeboden. Dit betekent ook dat alle microservices / back-end systemen potentieel moeten worden aangepast bij een hostname wijziging van de API Gateway (tenzij het vertalen van relatieve naar absolute URLs in de API Gateway wordt geregeld).

**Providing hyperlinks is explicitly NOT meant as an implementation of the often debated HATEOAS constraint [...]**
- Eens met deze stelling, maar hij moet m.i. iets anders geformuleerd worden. Ik lees hem in ieder geval als "Ookal zeggen Roy Fielding en het Richardson MM dat hyperlings voor HATEOAS worden gebruikt, is dat toch niet zo". Ik zou de tekst aanpassen naar "This design rule does explicitly NOT intend the use of hyperlinks as an implementation of the often debated HATEOAS constraint". Daarmee geef je expliciet aan dat het afwijken van het HATEOAS constraint een keuze is van deze specifieke design rule.

**Navigation controls are references to URIs within the scope of the originating API, i.e. these paths are specified in the same OpenAPI specification and thus residing on the same domain within the same base path.**
- URIs onder hetzelfde domein/base path hoeven niet in de zelfde OpenAPI specificatie te worden beschreven. Sommige API Gateway producten verlangen zelfs een aparte OpenAPI specificatie per root resource. Ik zou hem formuleren als "[...], i.e. these paths reside on the same domain within the same base path and are typically specified in the same OpenAPI specification".

**The only exception when navigation controls are allowed to point to other APIs is when they share governance. When doing so, the governing party must guarantee stability of inter-API links, which means the target operation of the link must never change within a major version of the originating API.**
- Zou dit niet meer een advies moeten zijn ivm een verplichting? Bijvoorbeeld bij het gebruiken van permalinks, zelfs elders gehost, kan je er vrij zeker van zijn dat deze niet wijzigen..

**API-XX: Apply the HAL media type when providing navigation controls**
- gingen we niet voor altijd HAL? Zo niet, zou ik daar ook dingen als embeds en andere zaken die HAL regelt aan toe voegen. Waarom zouden we het wel mogelijk maken om embeds op een andere manier toe te passen zonder HAL en navigatie controls niet?

**API-XX: Treat external links as regular resource attributes**
- Zou dit niet een advies moeten zijn ivm een verplichting?

**Providing the total count and/or last page of a collection should be avoided, since this may have a considerable impact on performance when dealing with larger collections. Therefore, providing such information or links is generally discouraged. Most often, this is not a problem since this does not add significant value for end users. Most modern user interfaces provide next/prev links only (e.g. a load more control).**
- Ik denk niet dat we vanuit de API design rules moeten spreken over value voor eindgebruikers. Volgens mij zou het meer een suggestie moeten zijn dat performance niet over het hoofd moet worden gezien, maar de requirements zullen van data set tot data set verschillen. Ik zou niet aangeven dat het vermeden moet worden, maar dat over performance nagedacht moet worden en dat de performance een beslissende factor kan zijn bij het maken van beslissingen.

2021-06-04 11:23 UTC, fsamwel commented
> Hypermedia relates to the use of hyperlinks
> Navigation controls are references to URIs within the scope of the originating API

Ik begrijp het verschil niet zo goed. Wanneer is iets hypermedia en wanneer navigation control?
Dé grote uitdaging die we met elkaar hebben voor wat betreft gegevensuitwisseling en het standaardiseren hierop is juist het koppelen van gegevens uit erschillende registraties of bronnen. Ook daar is hulp bij navigatie relevant. Denk aan navigeren van een persoon (BRP) naar een adres (BAG) of van een eigenaar (BRK) naar de persoon (BRP of HR).

2021-06-04 11:24 UTC, fsamwel commented
> Provide absolute URIs for hyperlinks

Waarom?
Ik zou voorstellen:
- gebruik relatieve links in interne links (binnen dezelfde API)
- gebruik templated absolute links voor externe links (naar een andere API), bijvoorbeeld "href": "{bagserverurl}/adressen/0200200000003734"

hiermee heb je geen last van proxies of gateways die ertussen zitten voor een client.

2021-06-04 11:25 UTC, fsamwel commented
> Navigation controls should not be intermixed with functional identification. Information resources represent real-world entities, which are functionally identified outside the context of an individual API. The same entities may be exchanged via other channels or other (versions of) APIs, providing the same functional identifiers.

De definitie van een "functionaliteit identificatie" is me niet echt duidelijk. Is een nummeraanduiding identificatie (BAG) een functionele of technische identificatie? En een kvk-nummer (HR)? Een zaakidentificatie? Een burgerservicenummer? Een documentnummer?
Als je dit soort identificaties niet in de betreffende Uris opneemt, maar in plaats daarvan een andere code, dan wordt die andere code gewoon de schaduw-identificatie. Wat los je op met het toevoegen van dubbele identificatie van elke resource? In de praktijk gaat toch iedereen een resource ophalen vanuit de functionele sleutel, want dat is wat in alle registraties bekend en opgeslagen is.
Of bedoel je met functionele identificatie postcode+huisnummer, geslachtsnaam+geboortedatum, enz.? (in dat geval ben ik het mee eens dat dit meestal niet handig is, vooral omdat deze "identificatie" kan wijzigen)

2021-06-04 11:28 UTC, fsamwel commented
> Only provide navigational links when there is a clear functional goal

Hoe weet de API wat voor de gebruiker een logische volgende informatiebehoefte is?

Denk aan een zaak, die heeft relaties naar een indiener, een behandelaar, een object waar het betrekking op heeft, een document, enz. Hoe kan je een selectie maken welke van deze relaties wel relevant zijn om aan te bieden als navigatie/link en welke niet?

2021-06-04 11:36 UTC, fsamwel commented
> Treat external links as regular resource attributes

Waarom? Naar mijn idee bevat de resource eigenschappen van de resource, inclusief relaties. En kunnen er daarnaast hyperlinks worden aangeboden naar andere resources. Waarom is er daarbij een onderscheid tussen interne en externe resources?
Ook is het lang niet altijd zo dat in het model vooraf duidelijk is of een relatie intern of extern is. Moet de relatie dan soms in de resource en soms in _links worden opgenomen? Bijvoorbeeld de eigenaar van een kadastraal object kan een ingeschreven natuurlijk persoon zijn (link naar BRP), ingeschreven niet-natuurlijk persoon of vestiging (link naar HR) of een niet-ingeschreven persoon (interne link binnen zelfde kadaster API. Dit speelt in heel veel systemen en registraties, denk aan vergunningen, belastingen, zaakregistratie, enz.

2021-06-25 13:17 UTC, joostfarla commented
> Ik begrijp het verschil niet zo goed. Wanneer is iets hypermedia en wanneer navigation control?
Dé grote uitdaging die we met elkaar hebben voor wat betreft gegevensuitwisseling en het standaardiseren hierop is juist het koppelen van gegevens uit erschillende registraties of bronnen. Ook daar is hulp bij navigatie relevant. Denk aan navigeren van een persoon (BRP) naar een adres (BAG) of van een eigenaar (BRK) naar de persoon (BRP of HR).

Vanuit informatie-perspectief liggen relaties niet tussen HTTP resources (URIs), maar tussen informatie-objecten. Objecten zoals deze in basisregistraties zijn opgenomen verwijzen naar elkaar op basis van object-identificatie, vaak conform een standaard zoals NEN3610. Om die reden hebben we ook een opmerking geplaatst over het verschil tussen functionele identificatie en resource URIs. Die kan mogelijk nog wel wat uitgebreider worden geformuleerd. Ook de opmerkingen over HATEOAS en links tussen APIs spelen hier overigens een rol. 

De design rule vwb absolute URIs heb ik verder genuanceerd om de essentie duidelijker te maken.

2021-06-25 13:18 UTC, merged