Lost #485 op
Geonovum/KP-APIs pull request #561
Opened 2023-02-08 16:29 UTC by strijm

2023-02-13 12:54 UTC, lvdbrink approved these changes

2023-02-13 12:56 UTC, lvdbrink commented
closes #485

2023-02-13 18:08 UTC, sweco-nlgemo requested changes

2023-02-14 08:33 UTC, lvdbrink approved these changes

2023-02-14 12:15 UTC, PB-GNM approved these changes
Ik heb hem op "approve" gezet "
Maar heb nog wel een vraag over deze zin:
"The provider shall be able to provide resources that do not have a geometry property and are related to resources that match the bounding box filter. "
Waarom is die opgenomen?

2023-02-14 12:24 UTC, PB-GNM approved these changes

2023-02-14 12:30 UTC, strijm commented
@PB-GNM Dit heb ik toegevoegd n.a.v. https://docs.opengeospatial.org/is/17-069r4/17-069r4.html#query-param-invalid requirement 24 C.

2023-02-15 08:23 UTC, merged