ontwikkelbranch voor definitieve versie geo module
Geonovum/KP-APIs pull request #598
Opened 2023-05-08 08:59 UTC by lvdbrink

Commentaar uit #597 verwerken. 

> In #597 staat nu nog 1 open punt. Als duidelijk is wat we daar mee doen kan ik dit ook verwerken en kan dit PR gereviewd/gemerged worden.

Inmiddels opgelost.

closes #597

2023-05-08 10:33 UTC, sweco-nlgemo approved these changes

2023-05-08 12:09 UTC, lvdbrink commented
Open punt in #597 nu ook opgelost. @strijm @PB-GNM graag jullie goedkeuring!

2023-05-08 14:09 UTC, strijm approved these changes
@lvdbrink ik zag bij toeval op regel 249 een typo: 'responsess', wil je die ook nog aanpassen?
Verder akkoord.

2023-05-08 14:40 UTC, PB-GNM commented on API-strategie-modules/geospatial/request-response.md
Met deze verandering staat er nog niet wat bedoeld werd. 
Het gaat er volgens mij niet om of er 1 enkele gemetrie geleverd wordt, maar dat er geometrien van het type "single geometry" worden geleverd. 
De "a" moet er dus toch uit. Misschien is het beter ook het woord type toe te voegen.
dus "if geometries of type single gemetry or multiple geometry are returned.

2023-05-08 14:56 UTC, PB-GNM requested changes
Het gaat er volgens mij niet om of er 1 enkele gemetrie geleverd wordt, maar dat er geometrien van het type "single geometry" worden geleverd.
De "a" moet er dus toch uit. Misschien is het beter ook het woord type toe te voegen.
dus "if geometries of type single geometry or multiple geometry are returned".

Ook ben ik het helaas nog niet eens met de noot over de het filteren met lange lijnen. Het noemen van het getal 200 m. is gevaarlijk. Dat is afhankelijk van de kans op een fout die je accepteert.   Hoe langer de lijnen hoe groter de kans op een fout. 
Verder speelt het gevaar volgens mij alleen als de filter geometrie in een ander CRS is dan de source geometrie.

2023-05-16 09:51 UTC, lvdbrink commented
Typo gecorrigeerd, zin over geometrietypen geherformuleerd en de suggestie van Pieter voor de note overgenomen. Graag nog 1x review!

2023-05-16 10:01 UTC, sweco-nlgemo approved these changes

2023-05-17 06:59 UTC, PB-GNM approved these changes

2023-05-17 07:52 UTC, strijm commented
@lvdbrink ik heb Lennard gevraagd even mee te kijken naar de aanpassing omtrent lange lijnen.

2023-05-17 10:27 UTC, strijm commented
Input van Lennard:

1.

> het is niet zo dat het probleem alleen optreedt als het CRS voor het filter anders is dan het CRS van de data. Het probleem treedt ook op bij gebruik van 1 CRS. Het is wel zo dat het effect afhankelijk is van het CRS waarin wordt gefilterd. Bij CRS84 treedt het probleem eerder op dan bij RD.

Dit komt overeen met https://github.com/Geonovum/KP-APIs/issues/597#issuecomment-1538107194.

Suggestie voor aanpassing:
> Spatial operations like intersects and within in combination with a filter geometry (e.g. bbox) or resource geometry containing long lines, may result in erroneous responses since a straight line between two coordinates in a CRS is, depending on the CRS, not a straight line in reality.


2.

> The default CRS for GeoJSON and for OGC API Features is CRS84 (OGC:CRS84), this is WGS 84 with coordinate order longitude-latitude. 

Dit is onjuist. 
Suggestie voor aanpassing:
> The default CRS for GeoJSON and for OGC API Features is CRS84 (OGC:CRS84), this CRS uses the WGS 84 datum with an ellipsoidal coordinate system in the order longitude-latitude.


3.

> New ensemble member CRSs may be released in future (e.g. ITRF2020 has been released as a realization for ITRF), these new realizations shall be used instead of older realizations (e.g. ITRF2014).

Suggestie voor aanpassing:

> New ensemble member CRSs may be released in future (e.g. ITRF2020 has been released as a realization for ITRF). These new realizations shall be used instead of older realizations in case of ITRF. In case of ETRF however, National Mapping Agencies have agreed on using ETRF2000 instead of newer realisations (e.g. ETRF2014).

2023-05-22 06:42 UTC, PB-GNM commented
Ik ben het helemaal eens met de 4 verbeteringen uit de input van lennard.

2023-05-22 07:03 UTC, lvdbrink commented
@strijm ik heb net de suggesties van jou/Lennard verwerkt. Wil je nog één keer kijken?

2023-05-22 12:56 UTC, merged